### PR TITLE
GQL-54: Updating ws package

### PR DESCRIPTION
**Pull request by dpesall**
# Overview

### What is the feature?

Updating ws npm package.

# Checklist

- [x] I have added automated tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by dpesall** [comment]
> Can we verify we actually use the `ws` library?

It doesn't appear to be imported anywhere outside of the `node_modules` folder, and I tried removing it and running an `npm install` followed by all the tests, and it still seemed to work just fine. So we may be fine with just removing it, but I can't say for certain if it would break something in the deployed environment.

**Comment by eudoroolivares2016** [comment]
I don't think we are using `ws` so my preference would be to just remove it. The `npm audit fix` that was done on this branch updated the `package-lock` version for `ws` and for the `ws` in the packages pulling in the older versions so we don't even need to actually bump the `ws` in the `package.json` file to fix this

**Review by eudoroolivares2016 — APPROVED** [review]

**Comment by macrouch** [comment]
If you aren't sure if it will break something when deployed, just deploy this branch to SIT and find out

**Comment by dpesall** [comment]
> If you aren't sure if it will break something when deployed, just deploy this branch to SIT and find out

Tested this branch with `ws` removed in SIT and I didn't have any issues from my testing.

**Review by bnp26 — APPROVED** [review]

**Review by macrouch — APPROVED** [review]

**Pull request merged**
