### PR TITLE
GQL-91: Added "standardProduct" to schema

### PR DESCRIPTION
**Pull request by bnp26**
# Overview

### What is the feature?

Allow "standardProduct" to be used in query params for collections queries.

### What is the Solution?

Added "standardProduct" to the collections schema.

### What areas of the application does this impact?

src/cmr/concepts/collection.js
src/types/collection.graphql

# Testing

### Reproduction steps

- **Environment for testing:** PROD
- **Collection to test with:** N/A

1. Pick the Standard Products portal
2. Click on the export collections button and then the CSV.
3. Ensure the collection list downloads properly.
4. Then Click on the export collections button again and then JSON.
5. Ensure the collection list downloads properly.

Graphql Testing
Ensure that querying with standardProduct as a query parameter does not return errors

QUERY: 

```
query ExportCollections($params: CollectionsInput) {
  collections(params: $params) {
    cursor
    count
    items {
      provider
      shortName
      version
      title
      standardProduct
      processingLevel
      platforms
      timeStart
      timeEnd
    }
  }
}
```

PARAMS:

```
{
  "params": {
    "includeHasGranules": true,
    "limit": 10,
    "standardProduct": true
  }
}

```

### Attachments

Please include relevant screenshots or files that would be helpful in reviewing and verifying this change.

# Checklist

- [N/A] I have added automated tests that prove my fix is effective or that my feature works
- [N/A] New and existing unit tests pass locally with my changes
- [x] I have performed a self-review of my own code
- [n/a] I have commented my code, particularly in hard-to-understand areas
- [N/A] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by eudoroolivares2016** [comment]
Remember to update the commits and name of this PR to `GQL-91` instead of EDSC-4306

**Comment by macrouch** [comment]
Please complete the PR template as well. Testing steps are very useful for reviewers trying to switch contexts to review your changes

**Review by macrouch — CHANGES_REQUESTED** [review]
This isn't working for me. Regardless of the value I pass in to the `standardProduct` parameter I get the same results back.

**Comment by bnp26** [comment]
> This isn't working for me. Regardless of the value I pass in to the `standardProduct` parameter I get the same results back.

Would not getting different/the same result back be in scope? I thought we just need to make sure the value was able to be accepted by graphql. This would be a cmr ticket if the results don't work right?

**Comment by macrouch** [comment]
> > This isn't working for me. Regardless of the value I pass in to the `standardProduct` parameter I get the same results back.
> 
> Would not getting different/the same result back be in scope? I thought we just need to make sure the value was able to be accepted by graphql. This would be a cmr ticket if the results don't work right?

First step is to verify that the parameter is being sent to CMR. Results coming back the same regardless of the parameter value would indicate it isn't

**Review by macrouch — APPROVED** [review]

**Pull request merged**
